sudo: required
services:
  - docker

before_install:
  - docker build -t skrill0/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skrill0/docker-react npm run test -- --coverage

language: generic 